name:                the-little-cppler-book
version:             0.1.0.0
github:              "helq"
license:             BSD3
author:              "Elkin Cruz"
maintainer:          "helq@live.de"
copyright:           "2018 Elkin Cruz"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         This package builds the tools necessary to create a pdf with
                     the style of "The Little Schemer".

dependencies:
- base >= 4.7 && < 5
- pandoc
- pandoc-types

# library:
#   source-dirs: src

ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -Wall 
  - -Wincomplete-uni-patterns 
  - -Wincomplete-record-updates 
  - -Wmissing-import-lists

executables:
  tlcppler-exe:
    main:            tlcppler.hs
    source-dirs:     maker-src/pandoc-filters

  loadcodeinoutput-exe:
    main:            loadcodeinoutput.hs
    source-dirs:     maker-src/pandoc-filters
    dependencies:
      - directory
      - filepath

  build-pdf-exe:
    main:            build-pdf.hs
    source-dirs:     maker-src
    dependencies:
      - shake
      - text
      - containers
#      - either
