-- app/runcppcode.hs
import Text.Pandoc.JSON
import System.Directory
import System.FilePath
import System.IO (hPutStrLn, stderr)
import Data.Maybe (fromMaybe)
import Development.Shake
import Development.Shake.FilePath ((-<.>), exe)
import Data.Monoid ((<>))

doInclude :: Block -> IO Block
doInclude cb@(CodeBlock (_, _, namevals) contents) =
  case lookup "layout" namevals of
       Just f -> do
         currentDir <- getCurrentDirectory
         let basedir = normalise $ currentDir </> ".." </> ".." </> ".."
         file_layout <- readFile $ basedir </> "code" </> "layouts" </> f
         let newcontent = unlines . fmap insertContent . lines $ file_layout
             num_id = fromMaybe "999" $ lookup "numid" namevals
             cpp_name = num_id <> "-code-autogenerated.cc"

         shake shakeOptions{shakeVerbosity=Silent} $
           compile (basedir </> "code" </> cpp_name) newcontent

         return cb
       Nothing -> return cb

  where
    contents' = lines contents
    (includes, mainbody) = if "..." `elem` contents'
                              then let (ics, mainc) = break ("..."==) contents'
                                    in (ics, tail mainc)
                              else ([], contents')

    insertContent line = case break (/= ' ') line of
                           -- TODO: modify so unlines doesn't put a newline at the end of the last line
                           (spaces, "---<<<") -> unlines $ fmap (spaces++) includes
                           (spaces, "===<<<") -> unlines $ fmap (spaces++) mainbody
                           _                  -> line

doInclude x = return x

compile :: FilePath -> String -> Rules ()
compile cpp_name content = do
  let cpp_out = cpp_name -<.> "out"
  --liftIO . hPutStrLn stderr $ normalise cpp_name
  --liftIO $ hPutStrLn stderr cpp_bin
  want [cpp_name, cpp_out]

  "/**/*.out" %> \out -> do
    let bin = out -<.> "bin" <.> exe
    need [bin]
    (Stdout output) <- cmd [bin]
    writeFile' out output

  "/**/*.cc" %> \out ->
    writeFile' out content

  ("/**/*.bin" <.> exe) %> \out -> do
    let incpp = out -<.> "cc"
    --liftIO . hPutStrLn stderr $ "HEY!"
    need [incpp]
    (Stdout output, Stderr errput) <- cmd "clang++" [incpp] ["-o", out]
    liftIO . hPutStrLn stderr $ output <> "\n" <> errput


main :: IO ()
main = toJSONFilter doInclude
